# Generated by Django 2.0.2 on 2018-02-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0002_auto_20180203_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='url_thumbnail',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
